spring:
  cloud:
    stream:
      kafka:
         binder:
            brokers: 106.12.26.193
            zk-nodes: 106.12.26.193
            auto-create-topics: true
  datasource:
    stock:
      url: jdbc:mysql://106.12.26.193:3306/mama-buy-stock
      username: root
      passowrd: 1234

sharding:
  jdbc:
    datasource:
      names: ds
      ds:
        url: jdbc:mysql://106.12.26.193:3306/mama-buy-trade
        username: root
        password: 123456


regCenter:
  serverList: 106.12.26.193:2181
  namespace: elastic-job-lite-springboot

stockJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 1
  shardingItemParameters: 0=SuZhou
